# Use root/example as user/password credentials
version: '3.1'

x-common-variables: &common-variables
  REACT_APP_SERVER_PORT: 8000

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - ./sqlfiles/:/docker-entrypoint-initdb.d/
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080
  server:
    restart: always
    image: python
    volumes:
      - ./server:/server
    build:
      context: .
      dockerfile: ./server/DockerfilePython
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD
      - PORT=8000
    depends_on:
      - db
    command: uvicorn server:app --proxy-headers --host 0.0.0.0 --port 8000

  react:
    image: react
    build:
      context: .
      dockerfile: ./dockerfile-python
    ports:
      - 3000:3000
    environment:
      <<: *common-variables
    volumes:
      - .:/ci_cd_final
    depends_on:
      - server
    command: npm start
    networks:
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge

volumes:
  dbdata6: