# Use root/example as user/password credentials
version: '3.1'

x-common-variables: &common-variables
  REACT_APP_SERVER_PORT: 8000

services:
  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
      - ./mongod.conf:/etc/mongod.conf
    command: mongod --noauth --config /etc/mongod.conf
    networks:
      - webappnetwork

  server:
    image: nodejs
    volumes:
      - ./server-mongo:/server-mongo
      - /server-mongo/node_modules
    build:
      context: .
      dockerfile: ./server-mongo/dockerfile-server
    restart: always
    ports:
      - 8000:8000
    environment:
      - DATABASE_CONNECTION
      - SERVER_PORT
    depends_on:
      - db
    command: node server.js
    networks:
      - webappnetwork

  react:
    image: react
    build:
      context: .
      dockerfile: ./dockerfile-nodejs
    ports:
      - 3000:3000
    environment:
      <<: *common-variables
    volumes:
      - .:/ci_cd_final
      - /ci_cd_final/node_modules
      - /ci_cd_final/server-mongo
    depends_on:
      - server
    command: npm start
    networks:
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge

volumes:
  dbdata6: